In [1]:
import pandas as pd

In [2]:
#Creating Dictionary from List (all the list should be of same size else it will throw an error )
data = {
    "Name" : ["Bhavika", "Chaitanya" , "Dharya"],
    "Age" :[21,22,16],
    "Marks" :[85, 92, 98]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

        Name  Age  Marks
0    Bhavika   21     85
1  Chaitanya   22     92
2     Dharya   16     98

In [23]:
#Creating dataframe using series
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([5,6]) #here series can be of different sizes
df2 = pd.DataFrame({
    "A" : s1,
    "B" : s2
})
print(df2)
#unequal length works for series because they have labels, and they can be used for alignment
#But Lists don't have index labels for alignment so, for lists pandas assumes row 0 of 'A' matches row 0 of 'B'

   A    B
0  1  5.0
1  2  6.0
2  3  NaN
3  4  NaN

In [5]:
#shape of dataframe
df.shape

(3, 3)

In [6]:
#info of dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [7]:
#all the columns
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [8]:
#accessing a single column
df['Name']

0      Bhavika
1    Chaitanya
2       Dharya
Name: Name, dtype: str

In [9]:
type(df['Name']) #A single column is a series in dataframe

pandas.Series

In [11]:
df[['Name' , 'Age']]

        Name  Age
0    Bhavika   21
1  Chaitanya   22
2     Dharya   16

In [13]:
#accessing rows
df.iloc[0]

Name     Bhavika
Age           21
Marks         85
Name: 0, dtype: object

In [15]:
df.iloc[[0],2]

0    85
Name: Marks, dtype: int64

In [16]:
df.iloc[0:2]

        Name  Age  Marks
0    Bhavika   21     85
1  Chaitanya   22     92

In [17]:
df.loc[0,'Name']

'Bhavika'

In [18]:
df.loc[0:1, 'Name' : 'Age'] #in loc slicing 'stop' is inclusive

        Name  Age
0    Bhavika   21
1  Chaitanya   22

In [19]:
df['Name'].value_counts()

Name
Bhavika      1
Chaitanya    1
Dharya       1
Name: count, dtype: int64

In [21]:
df[['Name']]

        Name
0    Bhavika
1  Chaitanya
2     Dharya

In [22]:
type(df[['Name']]) #a list of only one element would return a data frame not a series

pandas.DataFrame

In [24]:
#Axis in Dataframe
df

        Name  Age  Marks
0    Bhavika   21     85
1  Chaitanya   22     92
2     Dharya   16     98

In [27]:
df[['Marks' , 'Age']].mean(axis = 0)

Marks    91.666667
Age      19.666667
dtype: float64

In [28]:
df[['Marks', 'Age']].mean(axis = 1)

0    53.0
1    57.0
2    57.0
dtype: float64