In [48]:
import pandas as pd

In [49]:
#creating dataframes from lists
#all the list should be of same size else it will throw an error
data = {
    "first_name" : ["Bhavika" , "Chaitanya" , "Dharya"],
    "last_name" : ["Chopra" , "Garg" , "Chopra"],
    "age" : [21,22,16]
}
df = pd.DataFrame(data)
df

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [50]:
#creating dataframes from series
#unequal length works for series because they have labels, and they can be used for alignment
#But Lists don't have index labels for alignment so, for lists pandas assumes row 0 of 'A' matches row 0 of 'B'
price = pd.Series([10,50,100,150])
qnt = pd.Series([15,5,2,1])
df2 = pd.DataFrame({
    "prices" : price,
    "quantity" : qnt
})
df2

   prices  quantity
0      10        15
1      50         5
2     100         2
3     150         1

In [51]:
df

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [52]:
print(df.shape) #shape returns number of rows and columns
print(df.columns) #columns returns all the columns of the DF

(3, 3)
Index(['first_name', 'last_name', 'age'], dtype='str')

In [53]:
df.info() #info provides all the info about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first_name  3 non-null      str
 1   last_name   3 non-null      str
 2   age         3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [54]:
#accessing a single column
print(type(df['first_name']))
df['first_name'] #this gives us a series

<class 'pandas.Series'>

0      Bhavika
1    Chaitanya
2       Dharya
Name: first_name, dtype: str

In [55]:
print(df[['first_name']])
print(type(df[['first_name']])) #this gives us a dataframe even though we have mentioned just one column in the List

  first_name
0    Bhavika
1  Chaitanya
2     Dharya
<class 'pandas.DataFrame'>

In [56]:
#accessing multiple columns
df[['first_name','last_name']]

  first_name last_name
0    Bhavika    Chopra
1  Chaitanya      Garg
2     Dharya    Chopra

In [57]:
#accessing rows
df.iloc[[0],0] #0th row 0th column

0    Bhavika
Name: first_name, dtype: str

In [58]:
df.loc[[0] , 'first_name'] #0th row 0th column

0    Bhavika
Name: first_name, dtype: str

In [59]:
#slicing using iloc and loc
df.iloc[0:2] #inclusive : exclusive

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22

In [60]:
df.loc[0:2] #inclusive : inclusive

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [61]:
#axis in Dataframes
#axis = 0 -> Rows(Downwards) -> rows collapse here
#axis = 1 -> Columns(Horizontally) -> columns collapse here
df2

   prices  quantity
0      10        15
1      50         5
2     100         2
3     150         1

In [62]:
print(df2.sum(axis = 0))
print(df2.sum(axis = 1))

prices      310
quantity     23
dtype: int64
0     25
1     55
2    102
3    151
dtype: int64

In [63]:
df.head(2) #bydefault shows first 5 rows

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22

In [64]:
df.tail(2) #bydefault shows last 5 rows

  first_name last_name  age
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [65]:
df2.describe() #if there are no numeric columns it raises an error (Cannot describe a DataFrame without numeric columns)

           prices   quantity
count    4.000000   4.000000
mean    77.500000   5.750000
std     60.759087   6.396614
min     10.000000   1.000000
25%     40.000000   1.750000
50%     75.000000   3.500000
75%    112.500000   7.500000
max    150.000000  15.000000

In [66]:
df2.dtypes

prices      int64
quantity    int64
dtype: object

In [67]:
df2.astype(float)

   prices  quantity
0    10.0      15.0
1    50.0       5.0
2   100.0       2.0
3   150.0       1.0

In [68]:
#dataframes are mutable
df2.loc[3 , 'quantity'] = 5.0

In [69]:
df2

   prices  quantity
0      10        15
1      50         5
2     100         2
3     150         5

In [70]:
df2.index #returns the Index object representing row labels.

RangeIndex(start=0, stop=4, step=1)