In [53]:
import pandas as pd

In [54]:
#An Index is the row label system of a DataFrame.
#Columns label the vertical axis
# Index labels the horizontal axis
#When we create a DataFrame without specifying index: It assigns a rangeIndex (start = 0, stop = n, step = 1 )

In [55]:
data = {
    "first_name" : ["Bhavika" , "Chaitanya" , "Dharya"],
    "last_name" : ["Chopra" , "Garg" , "Chopra"],
    "age" : [21,22,16]
}
df = pd.DataFrame(data)

In [56]:
df

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [57]:
#inspecting index
df.index

RangeIndex(start=0, stop=3, step=1)

In [58]:
#length of index
len(df.index)

3

In [59]:
#check if index is unique
df.index.is_unique

True

In [60]:
df2 = pd.DataFrame({
    "price" : [100,200,300]
} , index = ['a','b','c'])

dates = pd.date_range('16-02-2026' , periods = 3)
df3 = pd.DataFrame({
    "price" : [100,200,300]
} , index = dates)

In [61]:
#types of indexes
# 1st -> RangeIndex (assigned by default if we don't mention)
print(type(df.index))
# 2nd -> Index (contains int, float, str)
print(type(df2.index))
# 3rd -> DateTime index (gives date)
print(type(df3.index))

<class 'pandas.RangeIndex'>
<class 'pandas.Index'>
<class 'pandas.DatetimeIndex'>

In [62]:
df

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [63]:
df.set_index('age' , inplace=True)

In [64]:
df.columns #removes the column from the columns

Index(['first_name', 'last_name'], dtype='str')

In [65]:
df2 = pd.DataFrame(data)

In [66]:
df2

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [67]:
df2.set_index('age' , inplace=True, drop = False) #by default drop = true, but if we do drop = false, the column will be present in columns
df2

    first_name last_name  age
age
21     Bhavika    Chopra   21
22   Chaitanya      Garg   22
16      Dharya    Chopra   16

In [68]:
df3 = pd.read_csv('survey_results_public.csv')
df3

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [69]:
#setting index during csv_read
df3 = pd.read_csv('survey_results_public.csv' , index_col = 'Respondent')
df3

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [70]:
#Resetting index
#by default drop = false, but if we do drop = true the index does not become a column and is completely dropped from the dataframe
df2

    first_name last_name  age
age
21     Bhavika    Chopra   21
22   Chaitanya      Garg   22
16      Dharya    Chopra   16

In [72]:
df2.reset_index(inplace = True, drop = True) #as we did drop=false while setting so we already had age as a column
df2

  first_name last_name  age
0    Bhavika    Chopra   21
1  Chaitanya      Garg   22
2     Dharya    Chopra   16

In [73]:
#Accessing a row by index label
df2.loc[0]

first_name    Bhavika
last_name      Chopra
age                21
Name: 0, dtype: object

In [74]:
df2.loc[0, 'last_name']

'Chopra'

In [77]:
df2.loc[0:2 , 'first_name' : 'last_name']

  first_name last_name
0    Bhavika    Chopra
1  Chaitanya      Garg
2     Dharya    Chopra

In [79]:
#Returns true if values stays the same or decreases
df4 = pd.DataFrame({
    "prices" : [100,200,300]
}, index = [30,20,10])
df4.index.is_monotonic_decreasing

True

In [82]:
#Duplicate index values
df5 = pd.DataFrame({
    "prices" : [100,200,300],
    "qnt" : [5,10,2]
}, index = ['A' , 'A' , 'B'])
df5

   prices  qnt
A     100    5
A     200   10
B     300    2

In [83]:
df5.loc['A'] #returns a dataframe

   prices  qnt
A     100    5
A     200   10

In [84]:
#sorting index
df4

    prices
30     100
20     200
10     300

In [85]:
df4.sort_index(ascending = True)

    prices
10     300
20     200
30     100

In [86]:
df4.sort_index(ascending = False) #temporarily, we have to do inplace = true

    prices
30     100
20     200
10     300