In [1]:
import pandas as pd

In [2]:
data = {
    "first_name" : ["Bhavika" , "Chaitanya" , "Dharya"],
    "last_name" : ["Chopra" , "Garg" , "Chopra"],
    "age" : [21,22,16],
    "marks" : [85,92,98]
}
df = pd.DataFrame(data)

In [3]:
df

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
1  Chaitanya      Garg   22     92
2     Dharya    Chopra   16     98

In [6]:
#creating mask
filt = df['last_name'] == 'Chopra'
#Applying mask
df[filt]

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
2     Dharya    Chopra   16     98

In [10]:
#Only selected rows with single column
filt = df['marks'] > 90
df.loc[filt , 'marks']

1    92
2    98
Name: marks, dtype: int64

In [11]:
#Only selected rows with multiple columns
filt = df['marks'] > 90
df.loc[filt , ['first_name','marks']]

  first_name  marks
1  Chaitanya     92
2     Dharya     98

In [12]:
#multiple conditions
#& -> Both conditions must be True
filt = (df['last_name'] == 'Chopra') & (df['marks'] > 90)
df.loc[filt , ['first_name','last_name','marks']]

  first_name last_name  marks
2     Dharya    Chopra     98

In [13]:
# | -> At least one condition must be True
filt = (df['last_name'] == 'Chopra') | (df['marks'] > 90)
df.loc[filt , ['first_name','last_name','marks']]

  first_name last_name  marks
0    Bhavika    Chopra     85
1  Chaitanya      Garg     92
2     Dharya    Chopra     98

In [14]:
# ~ -> Reverses boolean values
filt = df['last_name'] == 'Chopra'
df[~filt]

  first_name last_name  age  marks
1  Chaitanya      Garg   22     92

In [20]:
# where -> keeps structure and gives NaN or any values to the False rows
df.where(df['age'] > 18 , 0)

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
1  Chaitanya      Garg   22     92
2          0         0    0      0

In [18]:
#mask -> keeps structure and gives NaN or any value to the True rows
df.mask(df['age'] > 18 , 0)

  first_name last_name  age  marks
0          0         0    0      0
1          0         0    0      0
2     Dharya    Chopra   16     98

In [21]:
#between
df[df['age'].between(18,50)]

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
1  Chaitanya      Garg   22     92

In [23]:
#isin
df[df['age'].isin([18,21,16])]

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
2     Dharya    Chopra   16     98

In [27]:
df2 = pd.read_csv('survey_results_public.csv' , index_col = 'Respondent')
df2

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [29]:
df2.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

In [34]:
#str.contains
filt = df2['LanguageWorkedWith'].str.contains('Python')
df2.loc[filt , 'LanguageWorkedWith' ]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
84539    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
85738      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
86566      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
87739             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88212                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: str

In [51]:
#Filtering Rows with Missing Values
df2.loc[df2['LanguageWorkedWith'].isna(),   'LanguageWorkedWith']

Respondent
30       NaN
180      NaN
294      NaN
437      NaN
534      NaN
        ...
88062    NaN
88076    NaN
88601    NaN
88802    NaN
88816    NaN
Name: LanguageWorkedWith, Length: 1314, dtype: str

In [53]:
#Filtering Rows without Missing Values
df2.loc[df2['MainBranch'].notna() , 'MainBranch']

Respondent
1               I am a student who is learning to code
2               I am a student who is learning to code
3    I am not primarily a developer, but I write co...
4                       I am a developer by profession
5                       I am a developer by profession
Name: MainBranch, dtype: str

In [54]:
df

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
1  Chaitanya      Garg   22     92
2     Dharya    Chopra   16     98

In [56]:
#Filtering Using Index Equality
df.loc[df.index > 0]

  first_name last_name  age  marks
1  Chaitanya      Garg   22     92
2     Dharya    Chopra   16     98

In [61]:
#Using query
#we can use and or not inside query
#we can also compare python variables
df.query("first_name == 'Bhavika'")

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85

In [62]:
df.query("last_name == 'Chopra' or marks > 90")

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
1  Chaitanya      Garg   22     92
2     Dharya    Chopra   16     98

In [63]:
Lastname = "Chopra"
df.query("last_name == @Lastname")

  first_name last_name  age  marks
0    Bhavika    Chopra   21     85
2     Dharya    Chopra   16     98