In [37]:
import pandas as pd

In [38]:
data = {
    "first_name" : ["Bhavika" , "Chaitanya" , "Dharya"],
    "last_name" : ["Chopra" , "Garg" , "Chopra"],
    "age" : [21,22,16],
    "marks" : [85,92,98],
    "email" : ["BhavikaChopra@gmail.com" , "ChaitanyaGarg@gmail.com" , "DharyaChopra@gmail.com"]
}
df = pd.DataFrame(data)

In [39]:
df.columns

Index(['first_name', 'last_name', 'age', 'marks', 'email'], dtype='str')

In [40]:
#Updating columns
#Renaming column names -> Method 1 (this can't be used if we have lots of columns)
df.columns = ['first name' , 'last name' , 'age' , 'marks' , 'email']
df

  first name last name  age  marks                    email
0    Bhavika    Chopra   21     85  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22     92  ChaitanyaGarg@gmail.com
2     Dharya    Chopra   16     98   DharyaChopra@gmail.com

In [41]:
#Renaming column names -> Method 2 (Renaming only the columns we want)
df.rename(columns={'marks' : 'Percentage'} , inplace = True)
df

  first name last name  age  Percentage                    email
0    Bhavika    Chopra   21          85  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22          92  ChaitanyaGarg@gmail.com
2     Dharya    Chopra   16          98   DharyaChopra@gmail.com

In [42]:
#Using string operations on columns
df.columns = df.columns.str.capitalize()
df.columns = df.columns.str.replace(' ' , '_')

In [43]:
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          85  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22          92  ChaitanyaGarg@gmail.com
2     Dharya    Chopra   16          98   DharyaChopra@gmail.com

In [44]:
#Updating Rows
#Updating Entire Row
df.loc[0] = ['Bhavika' , 'Chopra' , 21 , 90 , 'BhavikaChopra@gmail.com'] #It is un-necessary as we only changed one value
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          90  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22          92  ChaitanyaGarg@gmail.com
2     Dharya    Chopra   16          98   DharyaChopra@gmail.com

In [45]:
#Updating specific cells
df.loc[2 , ['First_name' , 'Age']] = ['Anjali' , 45]
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          90  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22          92  ChaitanyaGarg@gmail.com
2     Anjali    Chopra   45          98   DharyaChopra@gmail.com

In [46]:
#Updating a single cell (can use loc but at is optimized for accessing scalar values)
df.at[2, 'First_name'] = "Dharya"
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          90  BhavikaChopra@gmail.com
1  Chaitanya      Garg   22          92  ChaitanyaGarg@gmail.com
2     Dharya    Chopra   45          98   DharyaChopra@gmail.com

In [48]:
#Updating Entire Column
df['Email'] = df['Email'].str.lower()
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          90  bhavikachopra@gmail.com
1  Chaitanya      Garg   22          92  chaitanyagarg@gmail.com
2     Dharya    Chopra   45          98   dharyachopra@gmail.com

In [49]:
#Update using conditions
df.loc[df['Age'] > 20 , 'Percentage'] = 95
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          95  bhavikachopra@gmail.com
1  Chaitanya      Garg   22          95  chaitanyagarg@gmail.com
2     Dharya    Chopra   45          95   dharyachopra@gmail.com

In [50]:
#Update using multiple conditions
filt = (df['First_name'] == 'Dharya') & (df['Last_name'] == 'Chopra')
df.loc[filt , 'Age'] = 16
df

  First_name Last_name  Age  Percentage                    Email
0    Bhavika    Chopra   21          95  bhavikachopra@gmail.com
1  Chaitanya      Garg   22          95  chaitanyagarg@gmail.com
2     Dharya    Chopra   16          95   dharyachopra@gmail.com

In [52]:
#Changing index label
df.rename(index = {0:'A' , 1:'B' , 2:'C' }, inplace = True)
df

  First_name Last_name  Age  Percentage                    Email
A    Bhavika    Chopra   21          95  bhavikachopra@gmail.com
B  Chaitanya      Garg   22          95  chaitanyagarg@gmail.com
C     Dharya    Chopra   16          95   dharyachopra@gmail.com

In [53]:
#Broadcasting
#Scalar Broadcasting
df['Percentage'] = 0
df

  First_name Last_name  Age  Percentage                    Email
A    Bhavika    Chopra   21           0  bhavikachopra@gmail.com
B  Chaitanya      Garg   22           0  chaitanyagarg@gmail.com
C     Dharya    Chopra   16           0   dharyachopra@gmail.com

In [54]:
#Conditional Broadcasting
df.loc[df['First_name'] == 'Bhavika', 'Percentage'] = 92
df

  First_name Last_name  Age  Percentage                    Email
A    Bhavika    Chopra   21          92  bhavikachopra@gmail.com
B  Chaitanya      Garg   22           0  chaitanyagarg@gmail.com
C     Dharya    Chopra   16           0   dharyachopra@gmail.com

In [55]:
#Multiple Row Broadcasting
df.loc[['B', 'C'] , 'Percentage'] = [95,98]
df

  First_name Last_name  Age  Percentage                    Email
A    Bhavika    Chopra   21          92  bhavikachopra@gmail.com
B  Chaitanya      Garg   22          95  chaitanyagarg@gmail.com
C     Dharya    Chopra   16          98   dharyachopra@gmail.com

In [56]:
#Column-wise Broadcasting
df['Percentage'] = df['Percentage'] + 1
df

  First_name Last_name  Age  Percentage                    Email
A    Bhavika    Chopra   21          93  bhavikachopra@gmail.com
B  Chaitanya      Garg   22          96  chaitanyagarg@gmail.com
C     Dharya    Chopra   16          99   dharyachopra@gmail.com