In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'Name': ['Bhavika', 'Chaitanya', 'Dharya'],
    'Country': ['India', 'United States', 'India'],
    'Salary': [50000, 80000, 60000],
    'Age' : [21,22,20]
})

df

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22
2     Dharya          India   60000   20

In [3]:
#apply() -> Series level
df['Name'].apply(len) #(Name is a series here)
#output is also a series

0    7
1    9
2    6
Name: Name, dtype: int64

In [5]:
#Custom transformation
df['Salary'].apply(lambda x : x + 1)

0    50001
1    80001
2    60001
Name: Salary, dtype: int64

In [7]:
#apply() -> Dataframe level
df.apply(len) #default axis = 0 (Rows collapse)

Name       3
Country    3
Salary     3
Age        3
dtype: int64

In [8]:
df.apply(len , axis=1) #axis = 1 (Columns collapse)

0    4
1    4
2    4
dtype: int64

In [11]:
#map
#For series
df['Country'] = df['Country'].map({
    'India' : 'IN',
    'United States' : 'US',
})
df #But unmapped becomes NaN so there is a better alternative

        Name Country  Salary  Age
0    Bhavika      IN   50000   21
1  Chaitanya      US   80000   22
2     Dharya      IN   60000   20

In [13]:
#Replace()
df['Country'] = df['Country'].replace({
    'IN' : 'India',
})
df #unmapped data remains the same

        Name Country  Salary  Age
0    Bhavika   India   50000   21
1  Chaitanya      US   80000   22
2     Dharya   India   60000   20