In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame({
    'Name': ['Bhavika', 'Chaitanya', 'Dharya'],
    'Country': ['India', 'United States', 'India'],
    'Salary': [50000, 80000, 60000],
    'Age' : [21,22,20]
})

df

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22
2     Dharya          India   60000   20

In [14]:
#Add columns using scalar
df['Tax'] = 0.2
df

        Name        Country  Salary  Age  Tax
0    Bhavika          India   50000   21  0.2
1  Chaitanya  United States   80000   22  0.2
2     Dharya          India   60000   20  0.2

In [15]:
#Column based on existing column
df['Bonus'] = df['Salary'] * 0.1
df

        Name        Country  Salary  Age  Tax   Bonus
0    Bhavika          India   50000   21  0.2  5000.0
1  Chaitanya  United States   80000   22  0.2  8000.0
2     Dharya          India   60000   20  0.2  6000.0

In [16]:
#Column using condition
df['High Earner'] = df['Salary'] > 60000
df

        Name        Country  Salary  Age  Tax   Bonus  High Earner
0    Bhavika          India   50000   21  0.2  5000.0        False
1  Chaitanya  United States   80000   22  0.2  8000.0         True
2     Dharya          India   60000   20  0.2  6000.0        False

In [17]:
#Inserting column at any position
df.insert(0, 'EmployeeID' , [101,102,103])
df

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus  High Earner
0         101    Bhavika          India   50000   21  0.2  5000.0        False
1         102  Chaitanya  United States   80000   22  0.2  8000.0         True
2         103     Dharya          India   60000   20  0.2  6000.0        False

In [18]:
#Dropping columns
df.drop(columns = ['High Earner'] , inplace=True)
df

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
0         101    Bhavika          India   50000   21  0.2  5000.0
1         102  Chaitanya  United States   80000   22  0.2  8000.0
2         103     Dharya          India   60000   20  0.2  6000.0

In [19]:
#Adding rows
#Adding a single row
df.loc[len(df)] = [104 , 'Aarav' , 'Canada' , 75000 , 24 , 0.2 , 7500]
df

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
0         101    Bhavika          India   50000   21  0.2  5000.0
1         102  Chaitanya  United States   80000   22  0.2  8000.0
2         103     Dharya          India   60000   20  0.2  6000.0
3         104      Aarav         Canada   75000   24  0.2  7500.0

In [20]:
#Adding multiple rows
new_rows = pd.DataFrame({
    'EmployeeID' : [105,106],
    'Name': ['Sandy' , 'Diva'],
    'Country': ['India', 'United States'],
    'Salary': [65000, 55000],
    'Age' : [24, 21],
    'Tax' : [0.2 , 0.2],
    'Bonus' : [6500, 5500]
})
df = pd.concat([new_rows , df] , ignore_index=True)
df

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
0         105      Sandy          India   65000   24  0.2  6500.0
1         106       Diva  United States   55000   21  0.2  5500.0
2         101    Bhavika          India   50000   21  0.2  5000.0
3         102  Chaitanya  United States   80000   22  0.2  8000.0
4         103     Dharya          India   60000   20  0.2  6000.0
5         104      Aarav         Canada   75000   24  0.2  7500.0

In [21]:
df['EmployeeID'] = [101,102,103,104,105,106]
df

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
0         101      Sandy          India   65000   24  0.2  6500.0
1         102       Diva  United States   55000   21  0.2  5500.0
2         103    Bhavika          India   50000   21  0.2  5000.0
3         104  Chaitanya  United States   80000   22  0.2  8000.0
4         105     Dharya          India   60000   20  0.2  6000.0
5         106      Aarav         Canada   75000   24  0.2  7500.0

In [22]:
#Dropping rows
df.drop(index = [0,1]) #requires inplace = true

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
2         103    Bhavika          India   50000   21  0.2  5000.0
3         104  Chaitanya  United States   80000   22  0.2  8000.0
4         105     Dharya          India   60000   20  0.2  6000.0
5         106      Aarav         Canada   75000   24  0.2  7500.0

In [23]:
#drop by position (if index is not 0,1,2)
df.drop(df.index[5])  #requires inplace = true

   EmployeeID       Name        Country  Salary  Age  Tax   Bonus
0         101      Sandy          India   65000   24  0.2  6500.0
1         102       Diva  United States   55000   21  0.2  5500.0
2         103    Bhavika          India   50000   21  0.2  5000.0
3         104  Chaitanya  United States   80000   22  0.2  8000.0
4         105     Dharya          India   60000   20  0.2  6000.0

In [24]:
df.drop(columns = 'EmployeeID' , inplace = True)
df

        Name        Country  Salary  Age  Tax   Bonus
0      Sandy          India   65000   24  0.2  6500.0
1       Diva  United States   55000   21  0.2  5500.0
2    Bhavika          India   50000   21  0.2  5000.0
3  Chaitanya  United States   80000   22  0.2  8000.0
4     Dharya          India   60000   20  0.2  6000.0
5      Aarav         Canada   75000   24  0.2  7500.0

In [26]:
#dropping using conditions
filt = df['Salary'] < 65000
df.drop(df.index[filt])

        Name        Country  Salary  Age  Tax   Bonus
0      Sandy          India   65000   24  0.2  6500.0
3  Chaitanya  United States   80000   22  0.2  8000.0
5      Aarav         Canada   75000   24  0.2  7500.0

In [28]:
#Reindex
#reorder index
df = df.reindex([2,3,4,0,1,5])
df

        Name        Country  Salary  Age  Tax   Bonus
2    Bhavika          India   50000   21  0.2  5000.0
3  Chaitanya  United States   80000   22  0.2  8000.0
4     Dharya          India   60000   20  0.2  6000.0
0      Sandy          India   65000   24  0.2  6500.0
1       Diva  United States   55000   21  0.2  5500.0
5      Aarav         Canada   75000   24  0.2  7500.0

In [29]:
#reorder columns 
df = df.reindex(columns = ['Name' , 'Age' , 'Salary' , 'Bonus' , 'Tax' , 'Country'])
df

        Name  Age  Salary   Bonus  Tax        Country
2    Bhavika   21   50000  5000.0  0.2          India
3  Chaitanya   22   80000  8000.0  0.2  United States
4     Dharya   20   60000  6000.0  0.2          India
0      Sandy   24   65000  6500.0  0.2          India
1       Diva   21   55000  5500.0  0.2  United States
5      Aarav   24   75000  7500.0  0.2         Canada