In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({
    'Name': ['Bhavika', 'Chaitanya', 'Dharya'],
    'Country': ['India', 'United States', 'India'],
    'Salary': [50000, 80000, 80000],
    'Age' : [21,22,20]
})

df

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22
2     Dharya          India   80000   20

In [9]:
#Sorting by column values
df.sort_values(by = 'Salary')

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22
2     Dharya          India   80000   20

In [10]:
#Descending
df.sort_values(by = 'Salary' , ascending = False)

        Name        Country  Salary  Age
1  Chaitanya  United States   80000   22
2     Dharya          India   80000   20
0    Bhavika          India   50000   21

In [11]:
#Sort by multiple columns
df.sort_values(['Salary' , 'Age'])

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
2     Dharya          India   80000   20
1  Chaitanya  United States   80000   22

In [14]:
#Different order per column
df.sort_values(['Salary' , 'Age'] , ascending = [False,True] , inplace=True)

In [17]:
#Sort by index
df.sort_index(inplace = True)
df

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22
2     Dharya          India   80000   20

In [18]:
df.sort_index(axis = 1)

   Age        Country       Name  Salary
0   21          India    Bhavika   50000
1   22  United States  Chaitanya   80000
2   20          India     Dharya   80000

In [21]:
df.nlargest(2,'Salary')

        Name        Country  Salary  Age
1  Chaitanya  United States   80000   22
2     Dharya          India   80000   20

In [22]:
df.nsmallest(2,'Salary')

        Name        Country  Salary  Age
0    Bhavika          India   50000   21
1  Chaitanya  United States   80000   22

In [23]:
df2 = pd.read_csv('survey_results_public.csv')
df2

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [25]:
df2.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

In [37]:
df2.loc[df2['ConvertedComp'].notna() , 'ConvertedComp'].sort_values(ascending = False)

88324    2000000.0
65062    2000000.0
88162    2000000.0
88264    2000000.0
17201    2000000.0
           ...
38814          0.0
12624          0.0
11206          0.0
40655          0.0
59361          0.0
Name: ConvertedComp, Length: 55823, dtype: float64

In [41]:
#Control NaN Position 
#na_position = 'first' / 'last'
df2['ConvertedComp'].sort_values(ascending = False , na_position = 'first')

88324    2000000.0
65062    2000000.0
88162    2000000.0
88264    2000000.0
17201    2000000.0
50517    2000000.0
61409    2000000.0
88321    2000000.0
37559    2000000.0
23275    2000000.0
40620    2000000.0
71733    2000000.0
71806    2000000.0
40693    2000000.0
40702    2000000.0
Name: ConvertedComp, dtype: float64