In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance'],
    'Employee': ['Bhavika', 'Chaitanya', 'Dharya', 'Anjali', 'Dheeraj'],
    'Salary': [60000, 80000, 50000, 52000, 70000]
})

df

  Department   Employee  Salary
0         IT    Bhavika   60000
1         IT  Chaitanya   80000
2         HR     Dharya   50000
3         HR     Anjali   52000
4    Finance    Dheeraj   70000

In [3]:
#Groupby Basics
#Split
df.groupby('Department') #Returns a groupby object

In [4]:
#Apply
df.groupby('Department')['Salary'].mean()

Department
Finance    70000.0
HR         51000.0
IT         70000.0
Name: Salary, dtype: float64

In [6]:
#Basic Aggregation
df.groupby('Department')['Salary'].median()

Department
Finance    70000.0
HR         51000.0
IT         70000.0
Name: Salary, dtype: float64

In [7]:
df.groupby('Department')['Salary'].count() #counts non-none values

Department
Finance    1
HR         2
IT         2
Name: Salary, dtype: int64

In [10]:
df.groupby('Department')['Salary'].size() #includes none values

Department
Finance    1
HR         2
IT         2
Name: Salary, dtype: int64

In [8]:
df.groupby('Department')['Salary'].min()

Department
Finance    70000
HR         50000
IT         60000
Name: Salary, dtype: int64

In [9]:
df.groupby('Department')['Salary'].max()

Department
Finance    70000
HR         52000
IT         80000
Name: Salary, dtype: int64

In [11]:
#Multiple Aggregations on One Column
df.groupby('Department')['Salary'].agg(['mean' , 'median' , 'min' , 'max'])

               mean   median    min    max
Department
Finance     70000.0  70000.0  70000  70000
HR          51000.0  51000.0  50000  52000
IT          70000.0  70000.0  60000  80000

In [12]:
#Different Aggregations for Different Columns
df.groupby('Department').agg({
    'Salary' : ['mean'],
    'Employee' : ['count']
})

             Salary Employee
               mean    count
Department
Finance     70000.0        1
HR          51000.0        2
IT          70000.0        2

In [13]:
#Custom Column Names
df.groupby('Department').agg(
    avg_salary = ('Salary' , 'mean'),
    max_salary = ('Salary' , 'max'),
    total_employees = ('Employee' , 'count')
)

            avg_salary  max_salary  total_employees
Department
Finance        70000.0       70000                1
HR             51000.0       52000                2
IT             70000.0       80000                2

In [14]:
#Grouping my multiple columns
df2 = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance'],
    'Employee': ['Bhavika', 'Chaitanya', 'Dharya', 'Anjali', 'Dheeraj'],
    'Gender' : ['F' , 'M' , 'M' , 'F' , 'M'],
    'Salary': [60000, 80000, 50000, 52000, 70000]
})
df2

  Department   Employee Gender  Salary
0         IT    Bhavika      F   60000
1         IT  Chaitanya      M   80000
2         HR     Dharya      M   50000
3         HR     Anjali      F   52000
4    Finance    Dheeraj      M   70000

In [17]:
grouped = df2.groupby(['Department' , 'Gender'])['Salary'].mean()
grouped

Department  Gender
Finance     M         70000.0
HR          F         52000.0
            M         50000.0
IT          F         60000.0
            M         80000.0
Name: Salary, dtype: float64

In [18]:
grouped.index #This has a multiIndex

MultiIndex([('Finance', 'M'),
            (     'HR', 'F'),
            (     'HR', 'M'),
            (     'IT', 'F'),
            (     'IT', 'M')],
           names=['Department', 'Gender'])

In [19]:
#as_index = True/False
df.groupby('Department' , as_index = False)['Salary'].max()

  Department  Salary
0    Finance   70000
1         HR   52000
2         IT   80000