In [8]:
import pandas as pd

In [9]:
trades = pd.DataFrame({
    "trade_id": [1, 2, 3 , 4],
    "product": ["CL", "NG", "ES" , "GC"],
    "quantity": [10, 5, 7 , 12]
})

products = pd.DataFrame({
    "product": ["CL", "NG", "ES"],
    "exchange": ["NYMEX", "NYMEX", "CME"]
})

In [10]:
trades

   trade_id product  quantity
0         1      CL        10
1         2      NG         5
2         3      ES         7
3         4      GC        12

In [11]:
products

  product exchange
0      CL    NYMEX
1      NG    NYMEX
2      ES      CME

In [12]:
#pd.merge() Basics
#inner
pd.merge(trades, products , on='product' , how= 'inner')
#Inner join keeps: Only rows that match in BOTH tables.

   trade_id product  quantity exchange
0         1      CL        10    NYMEX
1         2      NG         5    NYMEX
2         3      ES         7      CME

In [13]:
#left
#Keep everything from left table.
pd.merge(trades,products , on='product' , how= 'left')

   trade_id product  quantity exchange
0         1      CL        10    NYMEX
1         2      NG         5    NYMEX
2         3      ES         7      CME
3         4      GC        12      NaN

In [14]:
#right
# Keep everything from right table.
pd.merge(trades,products , on='product' , how= 'right')

   trade_id product  quantity exchange
0         1      CL        10    NYMEX
1         2      NG         5    NYMEX
2         3      ES         7      CME

In [15]:
#outer
#Keep EVERYTHING from both.
pd.merge(trades,products , on='product' , how= 'outer')

   trade_id product  quantity exchange
0         1      CL        10    NYMEX
1         3      ES         7      CME
2         4      GC        12      NaN
3         2      NG         5    NYMEX

In [16]:
#Mergin on index (matching indexes)
price_data = pd.DataFrame({
    "price": [100, 101, 102]
}, index=pd.to_datetime([
    "2024-01-01 09:00",
    "2024-01-01 09:01",
    "2024-01-01 09:02"
]))
sentiment_data = pd.DataFrame({
    "sentiment_score": [0.5, -0.2, 0.8]
}, index=pd.to_datetime([
    "2024-01-01 09:00",
    "2024-01-01 09:01",
    "2024-01-01 09:02"
]))

In [17]:
price_data

                     price
2024-01-01 09:00:00    100
2024-01-01 09:01:00    101
2024-01-01 09:02:00    102

In [18]:
sentiment_data

                     sentiment_score
2024-01-01 09:00:00              0.5
2024-01-01 09:01:00             -0.2
2024-01-01 09:02:00              0.8

In [20]:
#Joining
price_data.join(sentiment_data)

                     price  sentiment_score
2024-01-01 09:00:00    100              0.5
2024-01-01 09:01:00    101             -0.2
2024-01-01 09:02:00    102              0.8

In [21]:
#concatenation
day1 = pd.DataFrame({
    "product": ["CL", "NG"],
    "price": [100, 200]
})

day2 = pd.DataFrame({
    "product": ["ES", "GC"],
    "price": [300, 400]
})

In [22]:
day1

  product  price
0      CL    100
1      NG    200

In [23]:
day2

  product  price
0      ES    300
1      GC    400

In [24]:
pd.concat([day1, day2])

  product  price
0      CL    100
1      NG    200
0      ES    300
1      GC    400

In [25]:
pd.concat([day1, day2] , axis = 1)

  product  price product  price
0      CL    100      ES    300
1      NG    200      GC    400